### ISSUE TITLE
How to set other OVIRT::Client's other options key from Vagrantfile?

### ISSUE THREAD

**Issue by ruckuus** [myoung34/vagrant-ovirt3#17]
Is there a way to set these keys (rbovirt-0.0.31/lib/rbovirt.rb) from Vagrantfile:

@filtered_api   = options[:filtered_api]
@ca_cert_file   = options[:ca_cert_file]
@ca_cert_store  = options[:ca_cert_store]
@ca_no_verify   = options[:ca_no_verify]

I would like to ignore SSL error while connecting to my local oVirt server (it is in https, locally crafted certificate, etc). What I have currently done is to directly hack the rbovirt.rb and set @ca_no_verify to true so that it will ignore SSL errors.

**Comment by myoung34** [comment]
#7 talks about support for ``ca_cert_file `` and ``ca_cert_store``
``ca_no_verify`` is added in the next version of fog, which is pending. Once the latest gem is pushed out, there will be support for that. As for ``filtered_api``, I'm not sure what it provides, but if it's available through rbovirt, i'm open to a PR for support. Without a need for it or a way to verify it, I can't add that code myself

**Comment by myoung34** [comment]
#7 merged and adds support for no_verify. If you look at the PR in Fog, #3363, you'll see how to add the options for the others as well. I won't add them myself unless I have a personal need for them, but i'm 100% for someone issuing a PR for it here to add it.

**Comment by myoung34** [comment]
#23 added these missing options and is usable in 1.1.2, which is on rubygems as of today
