### ISSUE TITLE
cloud-init usage

### ISSUE THREAD

**Issue by lpenz** [myoung34/vagrant-ovirt3#29]
It would be great to be able to pass on the IP address to cloud-init, so that the same base template can be used to provision any Vagrant VM dynamically

**Comment by myoung34** [comment]
I've only scratched the surface of cloud-init (i've taken it for granted by using userdata at aws so much).
Out of curiosity what are you trying to achieve? I'm not sure I understand the issue.

I've had success with the openstack glance Centos 6.5 image and dynamic provisioning. 

For example here's how I hackishly used cloud-init to create a jenkins vm:

```
runcmd:
 - yum install -y java-1.7.0-openjdk 
 - echo jenkins.mydomain.local >/etc/hostname
 - sed -i.bak 's/127.0.0.1/127.0.0.1     jenkins.mydomain.local jenkins /g' /etc/hosts
 - hostname jenkins
 - echo $'search mydomain.local\nnameserver 192.168.2.1\nnameserver 192.168.2.113' > /etc/resolv.conf
 - wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
 - rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
 - yum install jenkins
 - service jenkins start
 - chkconfig jenkins on
 - iptables -I INPUT 2 -p tcp --dport 8080 -m state --state NEW,ESTABLISHED -j ACCEPT
 - service iptables save
 - usermod -aG root jenkins
```

**Comment by lpenz** [comment]
My idea is using vagrant to bring up a VM in ovirt for homologation/testing of deployment. I have a repository with a Vagrantfile and provisioning, and the vagrant commands work transparently with virtualbox and ovirt.

I think the only required change is that "vagrant up" should provision the provided IP address and other network configuration (default route?) instead of assuming that the template has the provided IP address configured. Having a single IP address in the template is not good when you have several people working on several VMs. DHCP could be used to provide the addresses, but in this case one would have to bring up the VM by hand, see the address and then configure it in the Vagrantfile - i.e. "vagrant up" would not be transparent.

...or am I missing something?

**Comment by myoung34** [comment]
The template should definitely not provide the IP, if it does then the template should be repackaged.
As for cloud-init it should stay out-of-the-loop too. Anything that uses an IP should get it dynamically.
I'm only familiar with the bash parts of cloud-init but you can get your IP by simply doing ``hostname -I``. 

Is there a section of cloud-init that isn't working?

**Comment by lpenz** [comment]
If the IP is dynamic, how can vagrant find out the IP of the VM that it has just brought up in ovirt, and use it for provisioning and ssh?

**Comment by myoung34** [comment]
vagrant just manages the VM, cloud-init provisions after. Vagrant would provide the VM, cloud-init would use it or retrieve it. 

Vagrant always knows the IP. Cloud-init may not.

**Comment by lpenz** [comment]
> vagrant just manages the VM, cloud-init provisions after.
> Vagrant would provide the IP, cloud-init would use it or retrieve it.

That's exactly what I need. But today, the ovirt plugin doesn't provide the IP to the VM as far as I can tell.

Bug vagrant can provision this initial IP when the VM is created, with cloud-init, as is documented in http://www.ovirt.org/REST-Api#How_can_I_run_a_custom_script_using_cloud-init.3F

**Comment by myoung34** [comment]
I'm still unsure why the IP needs to be given to cloud-init.
The ovirt plugin does provide the IP to the VM if you use something similar to:

```
+config.vm.network :private_network,
    :nictype => 'virtio', :netmask => '255.255.255.0', #normal network configuration
    :ovirt__ip => '192.168.2.99', :ovirt__network_name => 'ovirtmgmt', :ovirt__gateway => '10.101.55.1' # oVirt specific information, overwrites previous on oVirt provider
```

But beyond that, I can't think of any examples of where cloud-init would actively need the IP address of the box in a way that it can't get it. Since cloud-init runs after the box is up and running (with a network configuration) you could just use ``hostname -I`` to get it in the script.

Do you have a detailed use-case in which this isn't true?

**Comment by lpenz** [comment]
I've been reading the source code, and I think I might have a wrong understanding of how the plugin works...

If I don't provide the IP in the `config.vm.network` and the VM gets its IP through DHCP, is the plugin able to discover that IP and use it for rsync and ssh?

**Comment by myoung34** [comment]
Vagrant by core has to, otherwise it wouldn't be able to ssh and do the things it needs to such as run provisioners (which run locally in the VM). It's up to the plugin to provide a method to give that information to vagrant. This plugin does so by using the oVirt REST API to get its IP even if it was configured by DHCP.

**Comment by lpenz** [comment]
Perfect! I'll use DHCP instead of cloud-init then.
Sorry for the misunderstanding.
