### ISSUE TITLE
NameError when trying to create a VM with non existing template.

### ISSUE THREAD

**Issue by pparkkin** [myoung34/vagrant-ovirt3#30]
When trying to create a VM from a template that doesn't exist, the plugin errors out with this.

    /home/pppp/.vagrant.d/gems/gems/vagrant-ovirt3-1.2.0/lib/vagrant-ovirt3/action/create_vm.rb:40:in `call': uninitialized constant VagrantPlugins::OVirtProvider::Action::CreateVM::Error (NameError)

**Comment by myoung34** [comment]
I'll look into this tonight.

**Comment by myoung34** [comment]
Fixed with 51820b1
