### ISSUE TITLE
Missing nic_mac_addresses capability for Windows guests

### ISSUE THREAD

**Issue by pparkkin** [myoung34/vagrant-ovirt3#32]
Trying to bring up a Windows guest results in the following.

    The provider being used to start Windows ('ovirt3')
    doesn't support the "nic_mac_addresses" capability which is required
    for advanced networking to work with Windows guests. Please inform
    the author of the provider to add this feature.
    
    Until then, you must remove any networking configurations other
    than forwarded ports from your Vagrantfile for Vagrant to continue.

I have no explicit network configuration in my Vagrantfile.

I'll try to dig a little deeper to find out what exactly it's trying to do, and whether or not there's a way around it.

**Comment by pparkkin** [comment]
I found out what's going on. I'll start working on a fix when I get back to work next week.

**Comment by pparkkin** [comment]
Created PR #33

**Comment by myoung34** [comment]
Out of curiosity what version of vagrant are you using?
I ask because [this page](http://docs.vagrantup.com/v2/share/provider.html) only shows one required capability

**Comment by pparkkin** [comment]
$ vagrant --version
    Vagrant 1.7.2

The page you linked seems to be about Vagrant Share. I am not sure what it is exactly, but I am not using it.

The error comes during "Configuring and enabling network interfaces..." at start up. I'm guessing from around [here](https://github.com/mitchellh/vagrant/blob/efd1d5e11bfc5a72c7a1d1eae294b4751d841544/plugins/guests/windows/cap/configure_networks.rb#L55).
