### ISSUE TITLE
vagrant stuck on "Waiting for VM to get an IP address" in dhcp mode 

### ISSUE THREAD

**Issue by natman** [myoung34/vagrant-ovirt3#43]
...while vm is already up and got a dhcp address. it seems that vagrant doesn't know that the vm got this address and hangs up...
Here is my Vagrantfile network part:
  config.vm.network :private_network,
    :ip => '192.168.56.100', :nictype => 'virtio', :netmask => '255.255.255.0', #normal network configuration
    :ovirt__ip => '', :ovirt__network_name => 'br100', :ovirt__gateway => ''

**Comment by myoung34** [comment]
can you post some steps to reproduce and the error output? 
I'll try to simulate it

**Comment by natman** [comment]
On mint 17.3:
dpkg -i vagrant_1.8.1_x86_64.deb
mkdir vagrant-dockereclipseche-centos7
vagrant plugin install vagrant-ovirt3
vagrant up --provider=ovirt3

Vagrantfile =>
Vagrant.configure('2') do |config|
  config.vm.box = 'ovirt_vagrant_che'
  config.vm.box_url = 'https://github.com/myoung34/vagrant-ovirt3/blob/master/example_box/dummy.box?raw=true'

  config.vm.network :private_network,
    :ip => '192.168.56.100', :nictype => 'virtio', :netmask => '255.255.255.0', #normal network configuration
    :ovirt__ip => '', :ovirt__network_name => 'br100', :ovirt__gateway => '' # oVirt specific information, overwrites previous on oVirt provider

  config.vm.provider :ovirt3 do |ovirt|
    ovirt.template = 'ubuntu_12.04'
    ovirt.template_version = 'nic_ready'
    ovirt.cpus = 1
    ovirt.memory = 4096
    ovirt.console = 'vnc' #could also be 'spice'
    ovirt.url = 'https://myserver:443'
    ovirt.username = 'apc@internal'
    ovirt.password = 'passwd'
    ovirt.datacenter = 'Abes'
    ovirt.cluster = 'Dev'
    ovirt.ca_cert_file = '/etc/pki/ovirt-engine/ca.pem'
end

ovirt-engine is 3.6.2

Thank you

**Comment by natman** [comment]
edit : the issue seems not to be related to dhcp, because filling an IP leads to the same result...

**Comment by natman** [comment]
I tried with an other CentOS7 template in addition of ubuntu, but I am always stuck at the getting adress step, while the dhcp lease is valid. The same with static address instead...

**Comment by myoung34** [comment]
Are you able to successfully do a `vagrant up` at all?
There might be more to this. From what I see everything looks fine configuration-wise and I don't see anything that stands out. can you post the log output from a fresh `vagrant up` ?

**Comment by natman** [comment]
sure, I successuflly ran https://github.com/mickaelbaron/vagrant-dockereclipseche-ubuntu64-build with a simple vagrant up into virtualbox but I'd like now to do the same with ovirt

**Comment by andyswe** [comment]
This is what helped me:
Install ovrit guest tools to make the client vm's correctly report their ip back to rhevm/vagrant

http://daveostechtips.blogspot.se/2014/12/ovirt-35-guest-agent-install-and.html

**Comment by myoung34** [comment]
@natman I had no issues bringing any of my VMs up with the latest code. Can you try to use one from the `ovirt-image-repository` external provider?

**Comment by natman** [comment]
@andyswe : thanx, yes installing the ovirt-guest-agent into the template solved the issue, but how could I guess such a thing, where is it described for a newbie????
I meet now a new issue when running provision with vagrant up --ovirt-vagrant3 or vagrant up --provision
> 
config.vm.provision :shell, :path => "bootstrap.sh", :run => "always"
vagrant up  --provision 
> 

> 
Bringing

 machine 'default' up with 'ovirt3' provider...
==> default: VM is already up.
==> default: Rsyncing folder: /home/nblanchet/vagrant/vagrant-dockereclipseche-centos7-build/ => /vagrant
> 
As you can read, provionning never occurs, and there is not issue message, seems that the config.vm.provision is skipped.
the bootstrap.sh exists an is in the same folder, of course.

**Comment by myoung34** [comment]
the docs say to use `config.vm.provision :shell, path: "bootstrap.sh"`, try that?

the other option is to try `vagrant up --provision --provider=ovirt3`

**Comment by natman** [comment]
sure the file exists, the same file is used successfully with virtualbox provider. I tried with absloute path and with vagrant up --provision --provider=ovirt3, always the same

**Comment by myoung34** [comment]
@natman can you open a new issue saying that the shell provisioner isn't working as expected?
I like to keep the tickets clean =)

If I remember right I had issues getting user-data to work, which is what this should be using under the hood? It's been a really long time.

**Comment by myoung34** [comment]
#36 is what I suspect
