### ISSUE TITLE
Cannot remove VM. VM is running - on vagrant destroy

### ISSUE THREAD

**Issue by alclonky** [myoung34/vagrant-ovirt3#44]
vagrant destroy fails for CentOS 6 VM because VM hasn't finished shutting down.
on second vagrant destroy VM is down and it works
can you wait for the VM to shutdown before you delete it?

vagrant destroy
==> default: Removing VM...
/root/.vagrant.d/gems/gems/rbovirt-0.0.36/lib/rbovirt.rb:210:in `handle_fault': Cannot remove VM. VM is running. (OVIRT::OvirtException)
        from /root/.vagrant.d/gems/gems/rbovirt-0.0.36/lib/rbovirt.rb:148:in `rescue in http_delete'
        from /root/.vagrant.d/gems/gems/rbovirt-0.0.36/lib/rbovirt.rb:143:in `http_delete'
        from /root/.vagrant.d/gems/gems/rbovirt-0.0.36/lib/client/vm_api.rb:133:in `destroy_vm'
        from /root/.vagrant.d/gems/gems/fog-1.37.0/lib/fog/ovirt/requests/compute/destroy_vm.rb:7:in `destroy_vm'
        from /root/.vagrant.d/gems/gems/fog-1.37.0/lib/fog/ovirt/models/compute/server.rb:146:in `destroy'
        from /root/.vagrant.d/gems/gems/vagrant-ovirt3-1.5.0/lib/vagrant-ovirt3/action/destroy_vm.rb:17:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from /root/.vagrant.d/gems/gems/vagrant-ovirt3-1.5.0/lib/vagrant-ovirt3/action/connect_ovirt.rb:25:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:224:in `action_raw'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:199:in `block in action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:561:in `lock'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/destroy/command.rb:31:in `block in execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:235:in `block in with_target_vms'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:229:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:229:in `with_target_vms'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/destroy/command.rb:30:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/cli.rb:42:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:302:in `cli'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:174:in `<main>'

**Comment by myoung34** [comment]
Looks like there's no `wait_till_down.rb` file like [wait_till_up.rb](https://github.com/myoung34/vagrant-ovirt3/blob/master/lib/vagrant-ovirt3/action/wait_till_up.rb) so this should be an easy change

**Comment by myoung34** [comment]
If you can make the changes to #50 that dont include the stuff for `create_vm` i'll merge it and let it solve this one.

**Comment by myoung34** [comment]
This should be fixed in #54
