### ISSUE TITLE
Physical Memory Guaranteed cannot exceed Memory Size.

### ISSUE THREAD

**Issue by alclonky** [myoung34/vagrant-ovirt3#45]
Hi,
Can you please add an Option to set the Value for "Physical Memory Guaranteed" otherwise vagrant up failes when defining less memory then in Template:
 
vagrant up --provider=ovirt3
Bringing machine 'default' up with 'ovirt3' provider...
==> default: Creating VM with the following settings...
==> default:  -- Name:          mybackend2_1458833419.994753
==> default:  -- Cpus:          2
==> default:  -- Memory:        4000M
==> default:  -- Template:      linuxtemplate
==> default:  -- Version:       base version (1)
==> default:  -- Datacenter:    Default
==> default:  -- Cluster:       Default
==> default:  -- Console:       spice
Error while creating domain: Cannot add VM. Physical Memory Guaranteed cannot exceed Memory Size.

**Comment by myoung34** [comment]
I'll take a stab at this. Looks like [rbovirt supports it](https://github.com/abenari/rbovirt/blob/master/lib/ovirt/instance_type.rb) so it should be doable.

**Comment by myoung34** [comment]
Fixed in `1.7.0`
