### ISSUE TITLE
Windows Box - The given name is too long

### ISSUE THREAD

**Issue by alclonky** [myoung34/vagrant-ovirt3#47]
Hi,
its not possible to vagrant up a windows VM because there is a 15 characters Limit for the Hostname

Bringing machine 'default' up with 'ovirt3' provider...
==> default: Creating VM with the following settings...
==> default:  -- Name:          windowstest_1459496156.7505162
==> default:  -- Cpus:          2
==> default:  -- Memory:        4096M
==> default:  -- Template:      windowsvagrant
==> default:  -- Version:       base version (1)
==> default:  -- Datacenter:    Default
==> default:  -- Cluster:       Default
==> default:  -- Console:       spice
Error while creating domain: Cannot add VM. The given name is too long.

Thx for you help
Christian

**Comment by myoung34** [comment]
Fixed in `1.6.1`

**Comment by alclonky** [comment]
Is it possible you do this only for automated Names and not for self defined ones,
now you cant use longer Names for non Windows Boxes anymore?
