### ISSUE TITLE
Support for vagrant reload

### ISSUE THREAD

**Issue by alclonky** [myoung34/vagrant-ovirt3#49]
Vagrant attempted to call the action 'reload' on the provider
'oVirt (2d53a797-db41-4a4a-91a5-4fbbb56a4242)', but this provider doesn't support this action. This
is probably a bug in either the provider or the plugin calling this

is needed for plugins like vagrant-windows-domain

Thx a lot

**Comment by myoung34** [comment]
Added in `1.8.0`

**Comment by myoung34** [comment]
Make that `1.8.1`, i missed some validation.

**Comment by alclonky** [comment]
Your fix breaks vagrant up 
there is no action/provision

Bringing machine 'default' up with 'ovirt3' provider...
/root/.vagrant.d/gems/gems/vagrant-ovirt3-1.8.1/lib/vagrant-ovirt3/action.rb:31:in `block (2 levels) in action_up': cannot load such file -- /root/.vagrant.d/gems/gems/vagrant-ovirt3-1.8.1/lib/vagrant-ovirt3/action/provision (LoadError)
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:47:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:47:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from /root/.vagrant.d/gems/gems/vagrant-ovirt3-1.8.1/lib/vagrant-ovirt3/action/connect_ovirt.rb:25:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:224:in `action_raw'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:199:in `block in action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:561:in `lock'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

**Comment by myoung34** [comment]
Not sure how i missed that in my testing, removed it and pushed as `1.8.2`
