### ISSUE TITLE
Support for oVirt 4.0

### ISSUE THREAD

**Issue by alclonky** [myoung34/vagrant-ovirt3#63]
is oVirt 4.0 supported yet?
as there are API changes i think a newer rbovirt has to be used?
# https://github.com/abenari/rbovirt/pull/109

**Comment by mykaul** [comment]
The old, v3 API, will be still supported in 4.0.
Still, I highly recommend moving to the new Ruby GEM, which is simpler and more compliant (it is automatically generated from the REST definition, so it's always up-to-date).

**Comment by myoung34** [comment]
@mykaul how complete would you say the gem is? It looks to be a few months old so I'm just curious if there are any known issues with the oVirt API? Do you think it's as robust as rbovirt since they solve the same problem?

**Comment by mykaul** [comment]
@myoung34 first of all, it uses the v4 API - so it's not compatible with previous releases.
However, it is and will be as complete as it can get - it is, as the Python and Java SDKs are, automatically generated from the REST API definition, so it'll always be complete as can be and up-to-date as can be with the REST API of oVirt.

**Comment by myoung34** [comment]
You said that the v4 API supports v3 so I assumed the gem had the same ability, is that not true?

Also that's great about auto-generation, I've been browsing the modules

**Comment by mykaul** [comment]
No, let me clarify what I wrote above:
oVirt v4.0 will support both v3 and v4 of the API.
The new oVirt ruby gem will only support v4 of the API.

**Comment by myoung34** [comment]
I'm closing this as I've set up a new repo http://github.com/myoung34/vagrant-ovirt4 that will be the oVirt v4 provider.
I've recently set up an oVirt v4 host so I'll start cracking away. PR's welcome =)
